### ISSUE TITLE
Error installing odkr for R 4.0.0

### ISSUE THREAD

**Issue by lpmorenoc** [validmeasures/odkr#36]
Hi, 
Today I tried to install the package from GitHub but I am getting the following error. Is it because odkr does not work in R 4.0.0?
![image](https://user-images.githubusercontent.com/6476135/83557015-e5018b00-a4de-11ea-93c2-fdcc59e04405.png)

Error: Failed to install 'odkr' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr:
E> * checking for file 'C:\Users\lpmor\AppData\Local\Temp\RtmpS4ZmQp\remotes3d687afd4b29\validmeasures-odkr-33f920c/DESCRIPTION' ... OK
E> * preparing 'odkr':
E> * checking DESCRIPTION meta-information ... OK
E> Warning in grepl(e, files, perl = TRUE, ignore.case = TRUE) :
E>   PCRE pattern compilation error
E> 	'unrecognized character follows \'
E> 	at 'ODK Briefcase Storage$'
E> Error in grepl(e, files, perl = TRUE, ignore.case = TRUE) : 
E>   invalid regular expression '^\ODK Briefcase Storage$'
E> Execution halted

**Comment by ernestguevarra** [comment]
Hi. Thanks for your message. Can you let me know which version of odkr you are using and what your system OS is?

I have tested odkr with R4.0.0 in my system and it works as expected. So, I don't think that is the issue. But need to know your setup.

Thanks.

**Comment by lpmorenoc** [comment]
Hi @ernestguevarra.
The version of odkr I guess is the master branch on Github (but I am not sure of the exact version number); I am trying to install it  using devtools. I have Windows 10 Home and I was using R 4.0.0 (I did not have any issue with R. 3.6.0).

**Comment by ernestguevarra** [comment]
Thank you. I am checking now. I will get back to you right away once I've replicated the issue and offer solutions.

**Comment by ernestguevarra** [comment]
I have been able to replicate the problem. I think that you are correct that this is an R version problem but it is specific to Windows from what I can see. I will need to update the internals of the odkr to be compatible to R4.0.0. How time sensitive is your need for the package? I will aim to get a fix out latest tomorrow morning 10:00GMT. I will keep you posted.

**Comment by lpmorenoc** [comment]
I think for now I just used the old R version and it was working ok. So when the package is updated I will go back to R 4.0.0.
Thank you
