### PR TITLE
V0.3.2

### LINKED ISSUE #35: issues with odkr
I am trying to use the odkr package. I have used it before without any issue but today I updated odkBriefcase and I am getting the following error where apparently is not recognizing the URL although it is specified (I am using your example in https://validmeasures.org/odkr/), do you know what could be the issue?

Sorry if it is a basic question but I cannot make it work (it however looks to work in the command line.

Regards,

Patricia

### LINKED ISSUE #36: Error installing odkr for R 4.0.0
Hi, 
Today I tried to install the package from GitHub but I am getting the following error. Is it because odkr does not work in R 4.0.0?
image

Error: Failed to install 'odkr' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr:
E> * checking for file 'C:\Users\lpmor\AppData\Local\Temp\RtmpS4ZmQp\remotes3d687afd4b29\validmeasures-odkr-33f920c/DESCRIPTION' ... OK
E> * preparing 'odkr':
E> * checking DESCRIPTION meta-information ... OK
E> Warning in grepl(e, files, perl = TRUE, ignore.case = TRUE) :
E>   PCRE pattern compilation error
E> 	'unrecognized character follows \'
E> 	at 'ODK Briefcase Storage$'
E> Error in grepl(e, files, perl = TRUE, ignore.case = TRUE) : 
E>   invalid regular expression '^\ODK Briefcase Storage$'
E> Execution halted

### PR DESCRIPTION
**Pull request by ernestguevarra**
fixes #36; fixes #35

### CODE REVIEW

**Comment by lpmorenoc** [comment]
Great!

**Comment by ernestguevarra** [comment]
@lpmorenoc Sorry it took long to sort this out. In the end, it was actually a very simple (and silly) issue in a very obscure part of the code. But all seems to be working now. Please install this version now as I made some general improvements to the code since I made the earlier merge to correct the error you raised. Please let me know if you still have problems.

Just to say that within the next 2 months, I will be developing a package called `odktools` which will eventually replace this package. The `odktools` will perform similar functions as `odkr` but using an API to standard ODK Aggregate servers (ONA, Kobotoolbox, etc). I think there is still a use for having an ODK Briefcase API approach that `odkr` uses particularly if you are encrypting your forms (as this can only be decrypted using Briefcase) so I will keep `odkr` going but with very minimal support.

Thank you again for using the package.
